import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul class="circles">
        <div className="min-h-screen flex items-center justify-center px-5 bg-gradient-to-r from-black via-gray-800 to-gray-900 animate-gradient-x">
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
          <div className="relative w- max-w-lg">
              {children}
          </div>
        </div>
        </ul>
      </body>
    </html>
  )
}
